### PR TITLE
Conda package for vpolo

### PR DESCRIPTION
**Pull request by astrovsky01**
Additional method of install.

### CODE REVIEW

**Comment by k3yavi** [comment]
Hi @astrovsky01 ,

Thanks for the PR and adding vpolo to bioconda. 
I was wondering are you planning to use vpolo in your project soon ?
I am working on more memory and time optimized version of the the importer and would upload soon.
Some stats I am maintaining for the R version is [here](https://github.com/COMBINE-lab/EDS).
The current python version will work too, it's just a little slow to load. Let me know how urgent it is for your use case.

**Comment by astrovsky01** [comment]
I'm using it with Galaxy, as part of the alevin script. Alevin is wrapped and running, but needs vpolo to make the output useable in Galaxy. If the R version is preferred, I can make a wrapper for that too, I just need to be able to pull it from Bioconda.

**Comment by k3yavi** [comment]
Gotcha, if I may ask how updatable the wrapper script is ? The R code might already be wrapped inside the tximport package [here](https://github.com/mikelove/tximport) however it seems the bioconda version is very old and the relevant changes from the R package for Alevin has not made into the bioconductor release yet, although it's in the master branch on GitHub.

Not sure what's the right way to proceed here. I am open to suggestions and / or updating the python wrapper parallely.

**Comment by astrovsky01** [comment]
Assuming no major changes in the environment is necessary, the only thing that needs to be changed is the version string.

**Comment by k3yavi** [comment]
Thanks it makes sense. I'll talk to the tximport developer and would update you once I have the updated python version

**Comment by k3yavi** [comment]
Hi @astrovsky01  ,

So I just pushed the `v0.2.0` for vpolo and it should work with latest alevin output and [bioconda](https://github.com/bioconda/bioconda-recipes/pull/17553) once merged.
I think it can still use some more work in terms of it's sparse matrix output will add that into the next release.

**Comment by astrovsky01** [comment]
@k3yavi the update will be available tomorrow. The build worked for me.

**Comment by k3yavi** [comment]
Awesome thanks !. I checked about the R version, unfortunately it has to wait till October 30 that is with the official release of bioconductor. I'll keep you updated as we have the new version of tximport into bioconda.

**Pull request merged**
